# Generated by Django 4.2.6 on 2023-10-31 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_nada_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nada',
            new_name='Client',
        ),
    ]
