# Generated by Django 4.2.6 on 2023-10-31 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_nada_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
