# Generated by Django 4.2.6 on 2023-11-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='user_id',
            new_name='user',
        ),
    ]
